let mapleader = ","
set showcmd
set notimeout
set relativenumber
colorscheme darkblue

nnoremap <leader>w :w<return>
"nnoremap <leader>q :bdelete<return>
nnoremap <leader>q :q<return>
nnoremap <leader><leader> "

nnoremap <leader>sj :source $HOME/java.vim<cr> 
nnoremap <leader>ss :source $HOME/.vimrc<cr> 
nnoremap <leader>es :e $HOME/.vimrc<cr> 
nnoremap <leader>ej :e $HOME/java.vim<cr> 
nnoremap <leader>dj :sp $HOME/java.md<cr> 
syntax on
